### GENERAL SETTINGS ###

# Site settings
title: Learn Craps Yo
description: "how do I play craps, learn craps yo, iOS app"
analytics: UA-13302760-3 #Google analytics code in the format XX-nnnnnnnn-n
baseurl: "/learnCrapsYoLandingPageV2" #important: start with /
url: "http://craps.education"

# Build settings
markdown: kramdown
permalink: /:categories/:title
excerpt_separator: <!--more--> #use this in posts to define how long the excerpt of the post (that is shown on the Blog page) is

colors:  #in hex code if not noted else
  primary: "#FF001C" #"#F70031" 
  primary_rgb: "255,0,28" #"247,0,49" #rgb of the primary. Needed in some places for the transparency effect.  
  secondary: "#000000" #"#33004D"
  link: "#FF001C"
  link_hover: "#000000"
  footer_heading: "#ffffff"
  footer_content: "#bfc9d3"
  
  
### CONTACT SETTINGS ###

# Social networks usernames. Many more available: google-plus, flickr, linkedin, etc). Shown in footer.
social:
  - title: dribbble
    url:
  - title: facebook
    url:
  - title: twitter
    url: 
  - title: instagram
    url: 
  - title: tumblr
    url: 
    
# Postal address (add as many lines as necessary). Shown in footer and on Contact page.
address:
  - lines: 
    - Downtown
    - Chicago, IL
    - United States.
email: hello@solidtheme.com
tel: +34 8493-4893


### GENERAL DATA FOR VARIOUS LOCATIONS ###
    
# Members information. Shown on About page.
members:
  - name: Mike Land
    position: iOS Developer
    text: Once a Craps Dealer, now an iOS Develoer... Worlds collide
    img: team01.jpg
    social:
      - title: globe #use for email address
        url: http://mikepland.com
      - title: twitter
        url: http://twitter.com/mikepland
    
# Short text about your company. Shown in footer on every page and also separately on Home and Contact page.
about: "Learn Craps Yo, the best way to learn craps"

# Testimonial content. Shown on Home and About page. 
testimonial:
    message: "Craps is where it's at, Learn Craps Yo got me in the game."
    author: Tim O
    position: WEB DESIGNER
